# only suitable for english speakers
prot_seq_emoji_map = {
    'A': ':green_apple:',
    'B': ':banana:',
    'C': ':cherries:',
    'D': ':doughnut:',
    'E': ':elephant:',
    'F': ':fries:',
    'G': ':grapes:',
    'H': ':hamburger:',
    'I': ':icecream:',
    'J': ':jeans:',
    'K': ':key:',
    'L': ':lemon:',
    'M': ':mushroom:',
    'N': ':nose:',
    'O': ':octopus:',
    'P': ':pineapple:',
    'Q': ':princess:',
    'R': ':rabbit:',
    'S': ':strawberry:',
    'T': ':tomato:',
    'U': ':umbrella:',
    'V': ':volcano:',
    'W': ':watermelon:',
    'X': ':x:',
    'Y': ':sailboat:',
    '*': ':hand:',
    '-': ':wavy_dash:',
}

prot_scale = "ABCDEFGHIJKLMNOPQRSTUVWXY*-"
